/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BusinessCardWc {
    'address': string;
    'firstName': string;
    'lastName': string;
    'location': string;
    'ocupation': string;
    'telephone': string;
    'website': string;
  }
  interface BusinessCardWcAttributes extends StencilHTMLAttributes {
    'address'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'location'?: string;
    'ocupation'?: string;
    'telephone'?: string;
    'website'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BusinessCardWc': Components.BusinessCardWc;
  }

  interface StencilIntrinsicElements {
    'business-card-wc': Components.BusinessCardWcAttributes;
  }


  interface HTMLBusinessCardWcElement extends Components.BusinessCardWc, HTMLStencilElement {}
  var HTMLBusinessCardWcElement: {
    prototype: HTMLBusinessCardWcElement;
    new (): HTMLBusinessCardWcElement;
  };

  interface HTMLElementTagNameMap {
    'business-card-wc': HTMLBusinessCardWcElement
  }

  interface ElementTagNameMap {
    'business-card-wc': HTMLBusinessCardWcElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
